defaults: &defaults
  adapter: postgresql
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: wallaby_demo_development

test:
  <<: *defaults
  database: wallaby_demo_test
